### ISSUE TITLE
Application run failed java.lang.NoClassDefFoundError: java/beans/PropertyEditorSupport

### ISSUE THREAD

**Issue by siddhsql** [petr-panteleyev/jpackage-maven-plugin#10]
Hello,

I tried using this plugin to create an app installer. I am able to create a DMG installer for Mac and install it but when I try to run the application I get this error:

```
17:08:46.780 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
java.lang.NoClassDefFoundError: java/beans/PropertyEditorSupport
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.context.properties.bind.BindConverter$TypeConverterConverter.<clinit>(BindConverter.java:180)
	at org.springframework.boot.context.properties.bind.BindConverter$TypeConverterConversionService.<init>(BindConverter.java:157)
	at org.springframework.boot.context.properties.bind.BindConverter.<init>(BindConverter.java:63)
	at org.springframework.boot.context.properties.bind.BindConverter.getSharedInstance(BindConverter.java:133)
	at org.springframework.boot.context.properties.bind.BindConverter.get(BindConverter.java:126)
	at org.springframework.boot.context.properties.bind.Binder.<init>(Binder.java:191)
	at org.springframework.boot.context.properties.bind.Binder.<init>(Binder.java:161)
	at org.springframework.boot.context.properties.bind.Binder.<init>(Binder.java:140)
	at org.springframework.boot.context.properties.bind.Binder.get(Binder.java:537)
	at org.springframework.boot.context.properties.bind.Binder.get(Binder.java:522)
	at org.springframework.boot.context.config.ConfigDataEnvironment.<init>(ConfigDataEnvironment.java:141)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.getConfigDataEnvironment(ConfigDataEnvironmentPostProcessor.java:101)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at xxx.cli.App.main(App.java:21)
Caused by: java.lang.ClassNotFoundException: java.beans.PropertyEditorSupport
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 common frames omitted
Failed to launch JVM
```

Here is my complete config that I am using:

```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <outputDirectory>target/jmods</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputDirectory>target/jmods</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.panteleyev</groupId>
                <artifactId>jpackage-maven-plugin</artifactId>                
                <configuration>
                    <name>xxx</name>
                    <appVersion>1.0.0</appVersion>
                    <vendor>xxx.com</vendor>
                    <input>target/jmods</input>
                    <mainJar>${project.artifactId}-${project.version}.jar</mainJar>
                    <mainClass>xxx.cli.App</mainClass>                    
                    <addModules>jdk.incubator.vector</addModules>                    
                    <jLinkOptions>
                        <jLinkOption>--bind-services</jLinkOption>                        
                    </jLinkOptions>
                    <destination>target/dist</destination>                    
                    <javaOptions>
                        <option>--enable-preview</option>
                        <option>--add-modules jdk.incubator.vector</option>                        
                        <option>-Dfile.encoding=UTF-8</option>
                    </javaOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    
    <profiles>
        <profile>
            <id>win</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>                        
                        <configuration>
                            <icon>icons/icons.ico</icon>
                            <winMenu>true</winMenu>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>                        
                        <configuration>
                            <icon>icons/885430040.icns</icon>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

it looks like its not able to find a basic Java class which seems to suggest the runtime was not packaged properly?

I can see following files on the system:

```
$ ls /Applications/xxx.app/Contents/runtime/Contents/Home/lib/
classlist            jspawnhelper         libjava.dylib        libjli.dylib         libnet.dylib         libosxsecurity.dylib libverify.dylib      modules              server
jrt-fs.jar           jvm.cfg              libjimage.dylib      libjsig.dylib        libnio.dylib         libsyslookup.dylib   libzip.dylib         security             tzdb.dat
```

can you help me? thanks.

**Comment by petr-panteleyev** [comment]
Hello, this may give a hint:
https://stackoverflow.com/questions/74633025/java-modules-simple-spring-boot-application-create-custom-runtime
